# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
# - osx
julia:
  - 1.0
  - 1.2
  - nightly
matrix:
  allow_failures:
    - julia: nightly
#   - os: osx
# fast_finish: true
notifications:
  email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'using Pkg; Pkg.build()'
    - julia -e 'import Pkg; Pkg.add("Test")'
#   - if [[ `uname` = "Linux" ]]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi
    - julia -e 'using Pkg; Pkg.build("ICOADSDict"); Pkg.test("ICOADSDict"; coverage=true)'
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("ICOADSDict"); Pkg.test("ICOADSDict"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("ICOADSDict")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
# - julia -e 'cd(Pkg.dir("ICOADSDict")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
